version: '2'

services:
  zenika-resume:
    build: .
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      DATABASE_URL: postgres://postgres:zenikadev@postgres:5432/postgres
    ports: 
      - "3000:3000"
    links:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zenikadev
      PGDATA: /data/postgres
    volumes:
       - ./database.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - "5432:5432"
