version: "3.2"
services:
  postgres:
    image: postgres:11
    ports:
      - "5433:5432"
    networks:
      - netnet
  hasura:
    image: hasura/graphql-engine
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    networks:
      - netnet
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_APIS: "metadata,graphql"
      HASURA_GRAPHQL_ADMIN_SECRET: key
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
  app:
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
      - "hasura"
    build: .
    networks:
      - netnet
    environment:
      DMS_URL: http://hasura:8080/v1/graphql

networks:
  netnet:
    driver: bridge
