version: 2.1

jobs:
  ui-install-dependencies:
    docker:
      - image: node:5.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ui-dependencies-{{ checksum "package.json" }}
            - v1-ui-dependencies-
      - run:
          name: Download UI dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-ui-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  server-install-dependencies:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm --prefix server ci
      - persist_to_workspace:
          root: ./
          paths:
            - server/node_modules

  ui-lint:
    docker:
      - image: node:5.7
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run lint

  ui-build:
    docker:
      - image: node:5.7
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - build

  deploy:
    docker:
      - image: circleci/node:lts
    parameters:
      clever-app-id:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Package deployment artifact
          command: |
            mkdir ~/deploy
            cd ~/deploy
            cp -r ~/project/build build
            cp -r ~/project/server server
      - run:
          name: Deploy to Clever Cloud
          working_directory: ~/deploy
          command: |
            git config --global user.email "dsi-ext@zenika.com"
            git config --global user.name "Zenika"
            git init
            git add .
            git commit -m "deploy!"
            sudo npm install --global clever-tools
            clever login --token=$CLEVER_TOKEN --secret=$CLEVER_SECRET
            clever link << parameters.clever-app-id >>
            clever deploy --force

workflows:
  version: 2

  deploy:
    jobs:
      - ui-install-dependencies:
          filters:
            branches:
              only: staging-deploy
      - server-install-dependencies:
          filters:
            branches:
              only: staging-deploy
      # - ui-lint:
      #     requires:
      #       - ui-install-dependencies
      #     filters:
      #       branches:
      #         only: staging-deploy
      - ui-build:
          requires:
            - ui-install-dependencies
          filters:
            branches:
              only: staging-deploy
      - deploy:
          clever-app-id: app_41f798bc-7a32-4426-aa13-16d5a9326d30
          requires:
            - ui-build
            - server-install-dependencies
          context: clever-cloud-zenika
          filters:
            branches:
              only: staging-deploy
      - deploy:
          clever-app-id: app_69c5464d-594e-4c48-863b-07cd050dbfe4
          requires:
            - ui-build
            - server-install-dependencies
          context: clever-cloud-zenika-dev
          filters:
            branches:
              only: rewrite-back-for-dms

